# Generated by Django 5.0.1 on 2024-01-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Present', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
